### ISSUE TITLE
Scroll to first automatically after last cell

### ISSUE THREAD

**Issue by dilipiOSDeveloper** [BadhanGanesh/BJAutoScrollingCollectionView#1]
Scroll to first automatically after last cell

**Comment by BadhanGanesh** [comment]
@diliptiwari333 This is already happening in the existing codebase - the collection view will scroll to the first cell automatically when it is at the last cell. Do you face any issue in it?

**Comment by BadhanGanesh** [comment]
Closing this issue as this is not reproducible. Re-open this if you face this again. Do add a video of the issue when reopening again. Thanks.
